- type: entity
  id: CMUPathogenLanguagePreset
  name: Язык Патогена
  categories: [ HideSpawnMenu ]
  components:
  - type: Language
    spokenLanguages:
    - Pathogen
    understoodLanguages:
    - Pathogen
    currentLanguage: Pathogen
    defaultLanguage: Pathogen